// flow-typed signature: 0e97870292383aadbf127becfaefff32
// flow-typed version: <<STUB>>/jest-resolve_v^27.4.2/flow_v0.188.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-resolve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-resolve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-resolve/build/defaultResolver' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/fileWalkers' {
  declare module.exports: any;
}

declare module 'jest-resolve/build' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/isBuiltinModule' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/ModuleNotFoundError' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/nodeModulesPaths' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/resolver' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/shouldLoadAsEsm' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/types' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-resolve/build/defaultResolver.js' {
  declare module.exports: $Exports<'jest-resolve/build/defaultResolver'>;
}
declare module 'jest-resolve/build/fileWalkers.js' {
  declare module.exports: $Exports<'jest-resolve/build/fileWalkers'>;
}
declare module 'jest-resolve/build/index' {
  declare module.exports: $Exports<'jest-resolve/build'>;
}
declare module 'jest-resolve/build/index.js' {
  declare module.exports: $Exports<'jest-resolve/build'>;
}
declare module 'jest-resolve/build/isBuiltinModule.js' {
  declare module.exports: $Exports<'jest-resolve/build/isBuiltinModule'>;
}
declare module 'jest-resolve/build/ModuleNotFoundError.js' {
  declare module.exports: $Exports<'jest-resolve/build/ModuleNotFoundError'>;
}
declare module 'jest-resolve/build/nodeModulesPaths.js' {
  declare module.exports: $Exports<'jest-resolve/build/nodeModulesPaths'>;
}
declare module 'jest-resolve/build/resolver.js' {
  declare module.exports: $Exports<'jest-resolve/build/resolver'>;
}
declare module 'jest-resolve/build/shouldLoadAsEsm.js' {
  declare module.exports: $Exports<'jest-resolve/build/shouldLoadAsEsm'>;
}
declare module 'jest-resolve/build/types.js' {
  declare module.exports: $Exports<'jest-resolve/build/types'>;
}
declare module 'jest-resolve/build/utils.js' {
  declare module.exports: $Exports<'jest-resolve/build/utils'>;
}
