// flow-typed signature: 967848c1b7a82efcf0c9bab030d2f06f
// flow-typed version: <<STUB>>/postcss-preset-env_v^7.0.1/flow_v0.188.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-preset-env' {
  declare module.exports: any;
}
