// flow-typed signature: 5948dd7ca015d1dbc8db3510d96fca41
// flow-typed version: <<STUB>>/postcss-normalize_v^10.0.1/flow_v0.188.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-normalize' {
  declare module.exports: any;
}
